version: '3.8'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: peanut_sql
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./peanut_sql.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3306:3306"

  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: peanut_sql
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
    ports:
      - "8080:80"
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content/:/var/www/html/wp-content

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: wordpress_user
      PMA_PASSWORD: wordpress_password
    ports:
      - "8081:80"
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

volumes:
  mysql_data:
  wordpress_data:
